version: '3'

services:
  client:
    build: ./frontend
    ports:
      - 3000:3000
    volumes: 
      - ./frontend:/usr/src/app
      - node_modules:/usr/src/app/node_modules
      

  server:
    build: ./
    ports:
      - 3001:8000
    volumes:
      - ./express-server:/usr/src/server_app
      - node_modules_b:/usr/src/server_app/node_modules
    depends_on: 
      - mongo

  mongo:
    image: mongo
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"

volumes: 
  node_modules:
  node_modules_b:
  data: